require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - integration/bin/*
    - integration/db/schema.rb
    - vendor/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'lib/rspec/*_matcher.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/ApplicationRecord:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

Style/Documentation:
  Enabled: false
