inherit_from: '../.rubocop.yml'

AllCops:
  Exclude:
    - bin/*

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Rails/FilePath:
  EnforcedStyle: arguments

Style/ClassAndModuleChildren:
  Enabled: false
